"""add place_visits table

Revision ID: 456db4b486c8
Revises: 653c3ccd8c87
Create Date: 2026-03-18 13:45:26.083736

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "456db4b486c8"
down_revision: Union[str, Sequence[str], None] = "653c3ccd8c87"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "place_visits",
        sa.Column("trip_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("visited_at", sa.Date(), nullable=False),
        sa.Column("latitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("longitude", sa.Numeric(precision=10, scale=7), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), server_default=sa.text("now()"), nullable=True),
        sa.ForeignKeyConstraint(["trip_id"], ["trips.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_place_visits_trip_id"), "place_visits", ["trip_id"], unique=False)
    op.create_index(op.f("ix_place_visits_user_id"), "place_visits", ["user_id"], unique=False)
    op.create_index(op.f("ix_place_visits_visited_at"), "place_visits", ["visited_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_place_visits_visited_at"), table_name="place_visits")
    op.drop_index(op.f("ix_place_visits_user_id"), table_name="place_visits")
    op.drop_index(op.f("ix_place_visits_trip_id"), table_name="place_visits")
    op.drop_table("place_visits")
    # ### end Alembic commands ###
