"""add departure_city to trips

Revision ID: b80a9565cb34
Revises: f929fb672efc
Create Date: 2026-03-14 11:48:53.958427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b80a9565cb34"
down_revision: Union[str, Sequence[str], None] = "f929fb672efc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("trips", sa.Column("departure_city", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("trips", "departure_city")
    # ### end Alembic commands ###
