"""LightGBM LambdaRank training script.

Reads from ltr_training_pairs table (generated by generate_ltr_pairs.py).
Each query_id is one synthetic user profile scored against ~100 destinations.

Usage (inside Docker):
    python scripts/train_ranker.py [--holdout 0.2] [--ndcg-cutoff 10]

Pipeline:
  1. Build 39-dim destination feature matrix from DB
  2. Load ltr_training_pairs (query_id, destination_id, relevance_label 0..3)
  3. Build (user-hint × dest) feature vectors per pair
  4. Train LightGBM lambdarank grouped by query_id
  5. Evaluate NDCG@5 and NDCG@10 on held-out queries (not rows)
  6. Save model + metrics to model_registry
"""

import argparse
import json
import logging
import math
import os
import sys
import uuid
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

import joblib
import lightgbm as lgb
import numpy as np
import pandas as pd
from sqlalchemy import create_engine, text
from sqlalchemy.orm import Session, sessionmaker

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from app.services.feature_matrix import (  # noqa: E402
    build_destination_feature_matrix,
    get_feature_columns,
    save_feature_snapshot,
)

MODEL_SAVE_DIR = Path("/tmp/ml_models")

LGBM_PARAMS = {
    "objective": "lambdarank",
    "metric": "ndcg",
    "ndcg_eval_at": [5, 10],
    "learning_rate": 0.05,
    "num_leaves": 63,
    "max_depth": 8,
    "min_data_in_leaf": 20,
    "feature_fraction": 0.8,
    "bagging_fraction": 0.8,
    "bagging_freq": 5,
    "lambda_l1": 0.1,
    "lambda_l2": 0.5,
    "label_gain": [0, 1, 3, 7],
    "verbose": -1,
    "n_jobs": -1,
}

N_ROUNDS = 500
EARLY_STOPPING = 40


# ---------------------------------------------------------------------------
# Feature construction
# ---------------------------------------------------------------------------

ACTIVITY_TYPE_MAP = {
    "beach": "act_beach",
    "culture": "act_culture",
    "adventure": "act_active",
    "active": "act_active",
    "nature": "act_nature",
    "food": "act_food",
    "shopping": "act_shopping",
    "nightlife": "act_nightlife",
    "family": "act_family",
    "romance": "act_romance",
    "wellness": "act_romance",
    "urban": "act_culture",
    "business": "act_business",
}

BUDGET_TIER_RANGES = {
    "budget": (0.0, 0.35),
    "mid": (0.25, 0.60),
    "premium": (0.45, 0.80),
    "luxury": (0.65, 1.0),
}


def _build_pair_features(
    profile_snapshot: dict,
    dest_row: Any,
    feature_cols: list[str],
    travel_month: int,
) -> np.ndarray:
    """28-dim user features + 39-dim destination features = 67 total.

    User features are RAW preferences (not pre-computed fits) so LightGBM
    must learn the user × dest interaction itself. Pre-computing season_fit,
    safety_fit, visa_fit as user features would allow LightGBM to trivially
    memorise labels → best_iter=1 (the original circular label problem).

    Dims 0-7:   budget encoding
    Dims 8-12:  activity preferences (raw, ranked)
    Dims 13-16: raw constraint preferences (risk, visa, crowd, n_prefs)
    Dims 17-19: climate, origin, month
    Dims 20-24: month cyclical + climate_any
    Dims 25-27: interaction features (crowd_fit, climate_match, origin_proximity)
    Dims 28-66: destination feature vector (39 dims)
    """
    # Budget encoding
    budget_tier = str(profile_snapshot.get("budget_tier", "mid"))
    b_low, b_high = BUDGET_TIER_RANGES.get(budget_tier, (0.25, 0.60))
    budget_min_norm = float(profile_snapshot.get("budget_min_usd", 800)) / 20000.0
    budget_max_norm = float(profile_snapshot.get("budget_max_usd", 2000)) / 20000.0
    cost_index = float(dest_row.get("cost_index", 0.5))
    cost_mid = (b_low + b_high) / 2.0
    budget_fit = 1.0 - max(0.0, min(1.0, abs(cost_index - cost_mid) / 0.5))

    # Activity preferences — top-5 weighted match (raw interaction signal)
    vacation_prefs: list[str] = profile_snapshot.get("vacation_preferences_ranked") or []
    act_match = 0.0
    w_total = 0.0
    for rank, act in enumerate(vacation_prefs[:5], start=1):
        col = ACTIVITY_TYPE_MAP.get(act)
        if col and col in dest_row.index:
            w = 6 - rank
            act_match += w * float(dest_row[col])
            w_total += w
    act_match_norm = act_match / w_total if w_total > 0 else 0.0

    # Top-3 activity preference one-hot (which activities user wants)
    top3_beach = float(any(ACTIVITY_TYPE_MAP.get(a) == "act_beach" for a in vacation_prefs[:3]))
    top3_culture = float(any(ACTIVITY_TYPE_MAP.get(a) == "act_culture" for a in vacation_prefs[:3]))
    top3_active = float(any(ACTIVITY_TYPE_MAP.get(a) == "act_active" for a in vacation_prefs[:3]))
    top3_nature = float(any(ACTIVITY_TYPE_MAP.get(a) == "act_nature" for a in vacation_prefs[:3]))

    # Raw constraint preferences (LightGBM learns interaction with dest features)
    risk_tolerance = int(profile_snapshot.get("risk_tolerance", 3))
    risk_norm = float(risk_tolerance) / 5.0
    is_safety_sensitive = float(risk_tolerance <= 2)

    visa_tolerance = str(profile_snapshot.get("visa_tolerance", "any_visa"))
    visa_strictness = {"visa_free_only": 1.0, "evisa_ok": 0.5, "any_visa": 0.0}.get(visa_tolerance, 0.0)

    crowd_pref = float(profile_snapshot.get("crowd_preference", 3)) / 5.0
    n_prefs = float(len(vacation_prefs))

    # Climate preference encoding
    climate_prefs: list[str] = profile_snapshot.get("climate_preferences") or ["any"]
    wants_coastal = float(any(p in climate_prefs for p in ("tropical_warm", "mediterranean")))
    wants_mountain = float("cold_snow" in climate_prefs)
    climate_any = float("any" in climate_prefs)

    # Origin and month
    origin_lat = profile_snapshot.get("origin_lat")
    origin_lng = profile_snapshot.get("origin_lng")
    has_origin = float(origin_lat is not None)
    month_norm = float(travel_month) / 12.0
    # Month sine/cosine encoding (cyclical — Jan and Dec are adjacent)
    month_sin = math.sin(2 * math.pi * travel_month / 12)
    month_cos = math.cos(2 * math.pi * travel_month / 12)

    # Budget fit vs dest cost (matches independent_quality_score component 2)
    avg_daily = float(dest_row.get("avg_daily_cost_usd", 80.0))
    budget_min_usd = float(profile_snapshot.get("budget_min_usd") or 200)
    budget_max_usd = float(profile_snapshot.get("budget_max_usd") or 2000)
    duration_days = int(profile_snapshot.get("typical_duration_days") or 10)
    trip_cost = avg_daily * duration_days
    if budget_min_usd <= trip_cost <= budget_max_usd:
        trip_budget_fit = 1.0
    elif trip_cost < budget_min_usd:
        trip_budget_fit = max(0.3, 1.0 - (budget_min_usd - trip_cost) / max(budget_min_usd, 1) * 0.5)
    else:
        trip_budget_fit = max(0.0, 1.0 - (trip_cost - budget_max_usd) / max(budget_max_usd, 1))

    # Dim 25: crowd_fit — how well dest crowd_index matches user crowd_preference
    crowd_dest = float(dest_row.get("crowd_index_avg", 0.5))
    crowd_fit = 1.0 - abs(crowd_pref - crowd_dest)

    # Dim 26: climate_match — intersection of climate_prefs with dest attributes
    is_coastal = float(dest_row.get("is_coastal", 0))
    has_mountains = float(dest_row.get("has_mountains", 0))
    if "any" in climate_prefs:
        climate_match = 0.5
    else:
        hits = sum(
            [
                float(("tropical_warm" in climate_prefs or "mediterranean" in climate_prefs) and is_coastal > 0),
                float("cold_snow" in climate_prefs and has_mountains > 0),
                float("dry_desert" in climate_prefs and float(dest_row.get("safety_score", 0.5)) > 0.4),
            ]
        )
        climate_match = min(1.0, hits * 0.5)

    # Dim 27: origin_proximity — connectivity_score as accessibility proxy
    # (haversine requires origin_lng which is now included in profile snapshot)
    if origin_lat is not None and origin_lng is not None:
        proximity = float(dest_row.get("connectivity_score", 0.5))
    else:
        proximity = 0.5  # unknown origin → neutral

    user_vec = np.array(
        [
            b_low,  # 0  budget band low (tier)
            b_high,  # 1  budget band high (tier)
            budget_min_norm,  # 2  budget_min_usd normalised
            budget_max_norm,  # 3  budget_max_usd normalised
            cost_mid,  # 4  budget center (tier)
            budget_fit,  # 5  cost_index vs budget tier
            trip_budget_fit,  # 6  trip_cost (daily × days) vs budget range ← KEY interaction
            float(duration_days) / 45.0,  # 7  trip duration normalised
            act_match_norm,  # 8  weighted activity match (all 5 prefs)
            top3_beach,  # 9  wants beach (top-3 pref)
            top3_culture,  # 10 wants culture (top-3 pref)
            top3_active,  # 11 wants active/adventure (top-3 pref)
            top3_nature,  # 12 wants nature (top-3 pref)
            risk_norm,  # 13 risk tolerance normalised
            is_safety_sensitive,  # 14 risk <= 2
            visa_strictness,  # 15 visa strictness (0=any, 0.5=evisa, 1.0=free_only)
            crowd_pref,  # 16 crowd preference normalised
            wants_coastal,  # 17 prefers coastal/warm climate
            wants_mountain,  # 18 prefers cold/snow/mountain
            has_origin,  # 19 has origin city
            n_prefs,  # 20 number of activity preferences
            month_norm,  # 21 travel month (linear)
            month_sin,  # 22 travel month (sine — cyclical)
            month_cos,  # 23 travel month (cosine — cyclical)
            climate_any,  # 24 climate = any (flexible traveller)
            crowd_fit,  # 25 crowd_index vs crowd_preference (interaction)
            climate_match,  # 26 climate_prefs × is_coastal/has_mountains (interaction)
            proximity,  # 27 origin → dest accessibility via connectivity_score
        ],
        dtype=np.float32,
    )

    dest_vec = dest_row[feature_cols].values.astype(np.float32)
    return np.concatenate([user_vec, dest_vec])


# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------


def load_pairs(db: Session, dest_df: pd.DataFrame, feature_cols: list[str]) -> list[dict]:
    """Load ltr_training_pairs, join with dest features, build feature matrix."""
    logger.info("Loading ltr_training_pairs …")
    rows = db.execute(
        text(
            "SELECT query_id, destination_id, relevance_label, content_score, "
            "profile_snapshot, travel_month "
            "FROM ltr_training_pairs "
            "ORDER BY query_id, relevance_label DESC"
        )
    ).fetchall()
    logger.info("Loaded %d pairs from %d unique queries", len(rows), len(set(str(r.query_id) for r in rows)))

    dest_idx: dict[str, int] = {
        str(row["destination_id"]): int(i)
        for i, row in dest_df.iterrows()  # type: ignore[arg-type]
    }

    records = []
    skipped = 0
    for r in rows:
        dest_id_str = str(r.destination_id)
        if dest_id_str not in dest_idx:
            skipped += 1
            continue
        dest_row = dest_df.iloc[dest_idx[dest_id_str]]

        snapshot = r.profile_snapshot
        if isinstance(snapshot, str):
            snapshot = json.loads(snapshot)
        snapshot = snapshot or {}

        feat = _build_pair_features(snapshot, dest_row, feature_cols, int(r.travel_month))
        records.append(
            {
                "query_id": str(r.query_id),
                "label": int(r.relevance_label),
                "content_score": float(r.content_score),
                "features": feat,
            }
        )

    logger.info("Built %d feature vectors (skipped %d inactive dests)", len(records), skipped)
    return records


# ---------------------------------------------------------------------------
# Train / eval helpers
# ---------------------------------------------------------------------------


def split_by_query(records: list[dict], holdout: float, seed: int = 42) -> tuple[list, list]:
    """Split records into train/test by query_id (never split one query across sets)."""
    unique_qids = list({r["query_id"] for r in records})
    rng = np.random.default_rng(seed)
    rng.shuffle(unique_qids)
    n_test = max(1, int(len(unique_qids) * holdout))
    test_qids = set(unique_qids[:n_test])

    train = [r for r in records if r["query_id"] not in test_qids]
    test = [r for r in records if r["query_id"] in test_qids]
    return train, test


def to_lgb_dataset(records: list[dict], reference=None) -> tuple[lgb.Dataset, np.ndarray]:
    """Convert records → LightGBM Dataset with group sizes array."""
    X = np.stack([r["features"] for r in records]).astype(np.float32)
    y = np.array([r["label"] for r in records], dtype=np.int32)

    # Group sizes: consecutive runs of same query_id
    groups = []
    cur_qid = records[0]["query_id"]
    cur_count = 0
    for r in records:
        if r["query_id"] == cur_qid:
            cur_count += 1
        else:
            groups.append(cur_count)
            cur_qid = r["query_id"]
            cur_count = 1
    groups.append(cur_count)
    group_arr = np.array(groups, dtype=np.int32)

    ds = lgb.Dataset(X, label=y, group=group_arr, reference=reference, free_raw_data=False)
    return ds, group_arr


def ndcg_at_k(records: list[dict], scores: np.ndarray, k: int) -> float:
    """Compute mean NDCG@k over all queries."""

    def dcg(labels: np.ndarray, k: int) -> float:
        labels = labels[:k].astype(float)
        gains = 2.0**labels - 1.0
        discounts = np.log2(np.arange(2, len(labels) + 2, dtype=float))
        return float((gains / discounts).sum())

    ndcgs: list[float] = []
    cur_qid = records[0]["query_id"]
    start = 0

    def _eval_group(grp_records: list[dict], grp_scores: np.ndarray) -> None:
        y = np.array([r["label"] for r in grp_records])
        pred_order = np.argsort(-grp_scores)
        ideal_order = np.argsort(-y)
        actual = dcg(y[pred_order], k)
        ideal = dcg(y[ideal_order], k)
        if ideal > 0:
            ndcgs.append(actual / ideal)

    for i, r in enumerate(records):
        if r["query_id"] != cur_qid:
            _eval_group(records[start:i], scores[start:i])
            cur_qid = r["query_id"]
            start = i
    _eval_group(records[start:], scores[start:])

    return float(np.mean(ndcgs)) if ndcgs else 0.0


# ---------------------------------------------------------------------------
# Registry
# ---------------------------------------------------------------------------


def register_model(db: Session, model_path: str, metrics: dict, artifact_blob: bytes) -> str:
    db.execute(text("UPDATE model_registry SET is_active = false WHERE model_type = 'lambdarank'"))
    model_id = str(uuid.uuid4())
    db.execute(
        text(
            "INSERT INTO model_registry "
            "(id, name, version, model_type, is_active, metrics, model_path, model_blob, trained_at) "
            "VALUES (:id, 'ranker', 'ltr-v1', 'lambdarank', true, cast(:metrics as jsonb), :path, :blob, :now)"
        ),
        {
            "id": model_id,
            "metrics": json.dumps(metrics),
            "path": model_path,
            "blob": artifact_blob,
            "now": datetime.now(UTC),
        },
    )
    db.commit()
    return model_id


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main(holdout: float = 0.20, ndcg_cutoff: int = 10) -> None:
    db_url = os.environ.get("DATABASE_URL", "postgresql://postgres:postgres@localhost:5432/travel_planner")
    engine = create_engine(db_url)
    SessionLocal = sessionmaker(bind=engine)

    with SessionLocal() as db:
        # Check ltr_training_pairs exists and has data
        count = db.execute(text("SELECT COUNT(*) FROM ltr_training_pairs")).scalar()
        if not count:
            logger.error("ltr_training_pairs is empty — run generate_ltr_pairs.py first")
            sys.exit(1)
        logger.info("ltr_training_pairs: %d rows", count)

        logger.info("=== Phase 1: Destination feature matrix ===")
        dest_df = build_destination_feature_matrix(db)
        feature_cols = get_feature_columns()
        logger.info("Destinations: %d × %d features", len(dest_df), len(feature_cols))

        snap_id = save_feature_snapshot(db, feature_version=2, rows_count=len(dest_df), purpose="training")
        logger.info("Feature snapshot: %s", snap_id)

        logger.info("=== Phase 2: Load and featurise pairs ===")
        records = load_pairs(db, dest_df, feature_cols)

        n_feat = records[0]["features"].shape[0]
        from collections import Counter

        label_dist = Counter(r["label"] for r in records)
        logger.info("Pairs: %d  Features: %d  Labels: %s", len(records), n_feat, dict(sorted(label_dist.items())))

        logger.info("=== Phase 3: Train/test split by query ===")
        train_recs, test_recs = split_by_query(records, holdout=holdout)
        n_train_q = len({r["query_id"] for r in train_recs})
        n_test_q = len({r["query_id"] for r in test_recs})
        logger.info("Train: %d pairs / %d queries", len(train_recs), n_train_q)
        logger.info("Test:  %d pairs / %d queries", len(test_recs), n_test_q)

        logger.info("=== Phase 4: LightGBM LambdaRank ===")
        train_ds, _ = to_lgb_dataset(train_recs)
        val_ds, _ = to_lgb_dataset(test_recs, reference=train_ds)

        feature_names = [
            "u_budget_low",
            "u_budget_high",
            "u_budget_min_norm",
            "u_budget_max_norm",
            "u_budget_center",
            "u_budget_fit_tier",
            "u_trip_budget_fit",
            "u_duration_norm",
            "u_act_match",
            "u_top3_beach",
            "u_top3_culture",
            "u_top3_active",
            "u_top3_nature",
            "u_risk_norm",
            "u_safety_sensitive",
            "u_visa_strictness",
            "u_crowd_pref",
            "u_wants_coastal",
            "u_wants_mountain",
            "u_has_origin",
            "u_n_prefs",
            "u_month_norm",
            "u_month_sin",
            "u_month_cos",
            "u_climate_any",
            "u_crowd_fit",
            "u_climate_match",
            "u_origin_proximity",
        ] + feature_cols
        train_ds.set_feature_name(feature_names)
        val_ds.set_feature_name(feature_names)

        # LightGBM lambdarank NDCG at iter=1 is artificially inflated (pre-learning baseline).
        # We skip the first 20 iterations in early stopping to avoid choosing that false peak.
        # Real learning starts from iter~5 and converges around iter 80-150.
        eval_results: dict = {}
        callbacks = [
            lgb.log_evaluation(period=25),
            lgb.record_evaluation(eval_results),
        ]
        model = lgb.train(
            LGBM_PARAMS,
            train_ds,
            num_boost_round=N_ROUNDS,
            valid_sets=[val_ds],
            callbacks=callbacks,
        )

        # Manual best-iteration selection: skip first 10 rounds (artificially high NDCG)
        ndcg10_curve = eval_results.get("valid_0", {}).get("ndcg@10", [])
        if len(ndcg10_curve) > 10:
            best_iter_manual = int(np.argmax(ndcg10_curve[10:]) + 10) + 1
            logger.info(
                "Manual best_iter (skip first 10): %d  NDCG@10=%.4f  (iter1=%.4f)",
                best_iter_manual,
                ndcg10_curve[best_iter_manual - 1],
                ndcg10_curve[0],
            )
            # Re-train to that iteration
            model = lgb.train(
                LGBM_PARAMS,
                train_ds,
                num_boost_round=best_iter_manual,
            )
        else:
            best_iter_manual = model.num_trees()

        logger.info("=== Phase 5: Evaluate ===")
        X_test = np.stack([r["features"] for r in test_recs]).astype(np.float32)
        test_preds = np.asarray(model.predict(X_test), dtype=np.float64)

        ndcg5 = ndcg_at_k(test_recs, test_preds, k=5)
        ndcg10 = ndcg_at_k(test_recs, test_preds, k=ndcg_cutoff)
        logger.info("NDCG@5  = %.4f", ndcg5)
        logger.info("NDCG@10 = %.4f", ndcg10)

        if ndcg10 < 0.5:
            logger.warning("NDCG@10 %.4f < 0.5 threshold — below target quality", ndcg10)
        else:
            logger.info("NDCG@10 target met ✓")

        # Feature importance top-15
        imp = sorted(zip(feature_names, model.feature_importance("gain"), strict=False), key=lambda x: -x[1])[:15]
        logger.info("Top features by gain: %s", [(n, int(v)) for n, v in imp])

        logger.info("=== Phase 6: Save model ===")
        MODEL_SAVE_DIR.mkdir(parents=True, exist_ok=True)
        model_path = str(MODEL_SAVE_DIR / "ranker_ltr_v1.lgb")
        model.save_model(model_path)

        metrics = {
            "ndcg_at_5": round(ndcg5, 4),
            "ndcg_at_10": round(ndcg10, 4),
            "n_train_pairs": len(train_recs),
            "n_test_pairs": len(test_recs),
            "n_train_queries": n_train_q,
            "n_test_queries": n_test_q,
            "n_features": n_feat,
            "best_iteration": best_iter_manual,
            "n_estimators": int(model.num_trees()),
        }

        # Serialise artifact to bytes for persistent storage in DB (survives container restarts)
        import io

        artifact = {
            "model": model,
            "feature_cols": feature_cols,
            "feature_names": feature_names,
            "n_user_features": 28,
            "metrics": metrics,
        }
        buf = io.BytesIO()
        joblib.dump(artifact, buf)
        artifact_blob = buf.getvalue()
        logger.info("Artifact serialised: %.1f KB", len(artifact_blob) / 1024)

        joblib.dump(artifact, str(MODEL_SAVE_DIR / "ranker_ltr_v1.joblib"))

        model_id = register_model(db, model_path, metrics, artifact_blob)
        logger.info("Registered: id=%s", model_id)

        logger.info("=== Done: NDCG@5=%.4f  NDCG@10=%.4f  best_iter=%d ===", ndcg5, ndcg10, best_iter_manual)


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--holdout", type=float, default=0.20)
    parser.add_argument("--ndcg-cutoff", type=int, default=10)
    args = parser.parse_args()
    main(holdout=args.holdout, ndcg_cutoff=args.ndcg_cutoff)
