const DESTINATION_RU: Record<string, string> = {
  'Abu Dhabi': 'Абу-Даби',
  Agadir: 'Агадир',
  Agra: 'Агра',
  Aktau: 'Актау',
  Alanya: 'Аланья',
  Algarve: 'Алгарве',
  Algiers: 'Алжир',
  Almaty: 'Алматы',
  'Amalfi Coast': 'Амальфитанское побережье',
  Amsterdam: 'Амстердам',
  Anapa: 'Анапа',
  Ankara: 'Анкара',
  Antalya: 'Анталья',
  Aqaba: 'Акаба',
  Arkhangelsk: 'Архангельск',
  Ashgabat: 'Ашхабад',
  Astana: 'Астана',
  Astrakhan: 'Астрахань',
  Athens: 'Афины',
  Atacama: 'Атакама',
  Avarua: 'Аваруа',
  Azores: 'Азорские острова',
  Baku: 'Баку',
  Bali: 'Бали',
  Bangkok: 'Бангкок',
  Barcelona: 'Барселона',
  Beijing: 'Пекин',
  Berlin: 'Берлин',
  'Blue Mountains': 'Голубые горы',
  Bodrum: 'Бодрум',
  Brussels: 'Брюссель',
  Bucharest: 'Бухарест',
  Budapest: 'Будапешт',
  'Buenos Aires': 'Буэнос-Айрес',
  Cairo: 'Каир',
  Cancun: 'Канкун',
  'Cape Town': 'Кейптаун',
  Cebu: 'Себу',
  Colombo: 'Коломбо',
  Copenhagen: 'Копенгаген',
  Crete: 'Крит',
  Delhi: 'Дели',
  Doha: 'Доха',
  Dubai: 'Дубай',
  Dushanbe: 'Душанбе',
  Edinburgh: 'Эдинбург',
  'El Nido': 'Эль-Нидо',
  Florence: 'Флоренция',
  Frankfurt: 'Франкфурт',
  Fethiye: 'Фетхие',
  Fergana: 'Фергана',
  Fez: 'Фес',
  Fes: 'Фес',
  'George Town': 'Джорджтаун',
  Guangzhou: 'Гуанчжоу',
  Hanoi: 'Ханой',
  Helsinki: 'Хельсинки',
  'Hong Kong': 'Гонконг',
  Hurghada: 'Хургада',
  'Iceland Blue Lagoon': 'Голубая лагуна, Исландия',
  Istanbul: 'Стамбул',
  Jakarta: 'Джакарта',
  Jerusalem: 'Иерусалим',
  Kazan: 'Казань',
  'Koh Samui': 'Самуи',
  Komodo: 'Комодо',
  Kyoto: 'Киото',
  'Kuala Lumpur': 'Куала-Лумпур',
  Kutaisi: 'Кутаиси',
  Langkawi: 'Лангкави',
  'Las Vegas': 'Лас-Вегас',
  Lisbon: 'Лиссабон',
  Liverpool: 'Ливерпуль',
  'Lofoten Islands': 'Лофотенские острова',
  London: 'Лондон',
  'Los Angeles': 'Лос-Анджелес',
  Madrid: 'Мадрид',
  Male: 'Мале',
  Maldives: 'Мальдивы',
  Marrakech: 'Марракеш',
  Medellín: 'Медельин',
  'Mexico City': 'Мехико',
  Milan: 'Милан',
  Minsk: 'Минск',
  Moscow: 'Москва',
  'Monument Valley': 'Долина Монументов',
  Moorea: 'Муреа',
  Munich: 'Мюнхен',
  'New York': 'Нью-Йорк',
  Nice: 'Ницца',
  'Nizhniy Novgorod': 'Нижний Новгород',
  Osaka: 'Осака',
  Paris: 'Париж',
  Petra: 'Петра',
  Phuket: 'Пхукет',
  Porto: 'Порту',
  Prague: 'Прага',
  Pristina: 'Приштина',
  Reykjavik: 'Рейкьявик',
  Riga: 'Рига',
  Riyadh: 'Эр-Рияд',
  Rome: 'Рим',
  Rotterdam: 'Роттердам',
  Samarkand: 'Самарканд',
  'San Francisco': 'Сан-Франциско',
  'Santo Domingo Oeste': 'Санто-Доминго-Оэсте',
  Santorini: 'Санторини',
  Sapporo: 'Саппоро',
  Seoul: 'Сеул',
  Shanghai: 'Шанхай',
  'Sharm El Sheikh': 'Шарм-эш-Шейх',
  Singapore: 'Сингапур',
  Sochi: 'Сочи',
  Stockholm: 'Стокгольм',
  Sydney: 'Сидней',
  Tallinn: 'Таллин',
  Tashkent: 'Ташкент',
  Tbilisi: 'Тбилиси',
  'The Bronx': 'Бронкс',
  Tokyo: 'Токио',
  Ushuaia: 'Ушуая',
  Valletta: 'Валлетта',
  Venice: 'Венеция',
  Vienna: 'Вена',
  Warsaw: 'Варшава',
  Yerevan: 'Ереван',
  Zanzibar: 'Занзибар',
  Zurich: 'Цюрих',
};

const POI_EXACT_RU: Record<string, string> = {
  'Blue Mosque': 'Голубая мечеть',
  Colosseum: 'Колизей',
  'Eiffel Tower': 'Эйфелева башня',
  'Grand Bazaar': 'Гранд-базар',
  'Hagia Sophia': 'Айя-София',
  'Louvre Museum': 'Лувр',
  'Notre-Dame Cathedral': 'Собор Парижской Богоматери',
  'Sagrada Familia': 'Саграда Фамилия',
  'Tower of London': 'Лондонский Тауэр',
};

const hasCyrillic = (value: string) => /[А-Яа-яЁё]/.test(value);

export const localizeDestinationName = (name: string | null | undefined) => {
  if (!name || hasCyrillic(name)) return name ?? '';
  if (DESTINATION_RU[name]) return DESTINATION_RU[name];

  const rules: [string, string][] = [
    [' Islands', 'ские острова'],
    [' Island', ' остров'],
    [' Coast', 'ское побережье'],
    [' Mountains', 'ские горы'],
    [' National Park', ' национальный парк'],
    [' City', ''],
  ];
  for (const [suffix, ruSuffix] of rules) {
    if (name.endsWith(suffix)) {
      const base = name.slice(0, -suffix.length);
      return `${DESTINATION_RU[base] ?? base}${ruSuffix}`;
    }
  }
  return name;
};

export const localizePoiName = (name: string | null | undefined) => {
  if (!name || hasCyrillic(name)) return name ?? '';
  if (POI_EXACT_RU[name]) return POI_EXACT_RU[name];

  const rules: [RegExp, string][] = [
    [/^(.+) Museum$/, 'Музей {name}'],
    [/^(.+) Cathedral$/, 'Собор {name}'],
    [/^(.+) Church$/, 'Церковь {name}'],
    [/^(.+) Mosque$/, 'Мечеть {name}'],
    [/^(.+) Temple$/, 'Храм {name}'],
    [/^(.+) Palace$/, 'Дворец {name}'],
    [/^(.+) Castle$/, 'Замок {name}'],
    [/^(.+) Tower$/, 'Башня {name}'],
    [/^(.+) Bridge$/, 'Мост {name}'],
    [/^(.+) Square$/, 'Площадь {name}'],
    [/^(.+) Park$/, 'Парк {name}'],
    [/^(.+) Garden$/, 'Сад {name}'],
    [/^(.+) Beach$/, 'Пляж {name}'],
    [/^(.+) Market$/, 'Рынок {name}'],
  ];
  for (const [pattern, template] of rules) {
    const match = name.match(pattern);
    if (match) return template.replace('{name}', localizeDestinationName(match[1]));
  }
  return name;
};
