import re

DESTINATION_RU: dict[str, str] = {
    "Abu Dhabi": "Абу-Даби",
    "Agadir": "Агадир",
    "Agra": "Агра",
    "Aktau": "Актау",
    "Alanya": "Аланья",
    "Algarve": "Алгарве",
    "Algiers": "Алжир",
    "Almaty": "Алматы",
    "Amalfi Coast": "Амальфитанское побережье",
    "Amsterdam": "Амстердам",
    "Anapa": "Анапа",
    "Ankara": "Анкара",
    "Antalya": "Анталья",
    "Aqaba": "Акаба",
    "Arkhangelsk": "Архангельск",
    "Ashgabat": "Ашхабад",
    "Astana": "Астана",
    "Astrakhan": "Астрахань",
    "Athens": "Афины",
    "Azores": "Азорские острова",
    "Baku": "Баку",
    "Bali": "Бали",
    "Bangkok": "Бангкок",
    "Barcelona": "Барселона",
    "Beijing": "Пекин",
    "Berlin": "Берлин",
    "Blue Mountains": "Голубые горы",
    "Bodrum": "Бодрум",
    "Brussels": "Брюссель",
    "Bucharest": "Бухарест",
    "Budapest": "Будапешт",
    "Buenos Aires": "Буэнос-Айрес",
    "Cairo": "Каир",
    "Cancun": "Канкун",
    "Cape Town": "Кейптаун",
    "Cebu": "Себу",
    "Colombo": "Коломбо",
    "Copenhagen": "Копенгаген",
    "Crete": "Крит",
    "Delhi": "Дели",
    "Doha": "Доха",
    "Dubai": "Дубай",
    "Dushanbe": "Душанбе",
    "Edinburgh": "Эдинбург",
    "El Nido": "Эль-Нидо",
    "Florence": "Флоренция",
    "Frankfurt": "Франкфурт",
    "Fethiye": "Фетхие",
    "Fez": "Фес",
    "Guangzhou": "Гуанчжоу",
    "Hanoi": "Ханой",
    "Helsinki": "Хельсинки",
    "Hong Kong": "Гонконг",
    "Hurghada": "Хургада",
    "Iceland Blue Lagoon": "Голубая лагуна, Исландия",
    "Istanbul": "Стамбул",
    "Jakarta": "Джакарта",
    "Jerusalem": "Иерусалим",
    "Kazan": "Казань",
    "Koh Samui": "Самуи",
    "Komodo": "Комодо",
    "Kyoto": "Киото",
    "Kuala Lumpur": "Куала-Лумпур",
    "Kutaisi": "Кутаиси",
    "Langkawi": "Лангкави",
    "Las Vegas": "Лас-Вегас",
    "Lisbon": "Лиссабон",
    "Lofoten Islands": "Лофотенские острова",
    "London": "Лондон",
    "Los Angeles": "Лос-Анджелес",
    "Madrid": "Мадрид",
    "Male": "Мале",
    "Maldives": "Мальдивы",
    "Marrakech": "Марракеш",
    "Mexico City": "Мехико",
    "Milan": "Милан",
    "Minsk": "Минск",
    "Moscow": "Москва",
    "Munich": "Мюнхен",
    "New York": "Нью-Йорк",
    "Nice": "Ницца",
    "Nizhniy Novgorod": "Нижний Новгород",
    "Osaka": "Осака",
    "Paris": "Париж",
    "Petra": "Петра",
    "Phuket": "Пхукет",
    "Porto": "Порту",
    "Prague": "Прага",
    "Reykjavik": "Рейкьявик",
    "Riga": "Рига",
    "Riyadh": "Эр-Рияд",
    "Rome": "Рим",
    "Samarkand": "Самарканд",
    "San Francisco": "Сан-Франциско",
    "Santorini": "Санторини",
    "Sapporo": "Саппоро",
    "Seoul": "Сеул",
    "Shanghai": "Шанхай",
    "Sharm El Sheikh": "Шарм-эш-Шейх",
    "Singapore": "Сингапур",
    "Sochi": "Сочи",
    "Stockholm": "Стокгольм",
    "Sydney": "Сидней",
    "Tallinn": "Таллин",
    "Tashkent": "Ташкент",
    "Tbilisi": "Тбилиси",
    "Tokyo": "Токио",
    "Ushuaia": "Ушуая",
    "Valletta": "Валлетта",
    "Venice": "Венеция",
    "Vienna": "Вена",
    "Warsaw": "Варшава",
    "Yerevan": "Ереван",
    "Zanzibar": "Занзибар",
    "Zurich": "Цюрих",
}

_CYRILLIC_RE = re.compile("[А-Яа-яЁё]")


def translate_destination_name(name: str | None) -> str | None:
    if not name or _CYRILLIC_RE.search(name):
        return name
    if name in DESTINATION_RU:
        return DESTINATION_RU[name]
    replacements = [
        (" Islands", "ские острова"),
        (" Island", " остров"),
        (" Coast", "ское побережье"),
        (" Mountains", "ские горы"),
        (" National Park", " национальный парк"),
        (" City", ""),
    ]
    for suffix, ru_suffix in replacements:
        if name.endswith(suffix):
            base = name[: -len(suffix)]
            return f"{DESTINATION_RU.get(base, base)}{ru_suffix}"
    return name
