import re

DESTINATION_RU: dict[str, str] = {
    "Abu Dhabi": "Абу-Даби",
    "Accra": "Аккра",
    "Addis Ababa": "Аддис-Абеба",
    "Agadir": "Агадир",
    "Agra": "Агра",
    "Aktau": "Актау",
    "Aktobe": "Актобе",
    "Alanya": "Аланья",
    "Algarve": "Алгарве",
    "Algiers": "Алжир",
    "Almaty": "Алматы",
    "Alsace": "Эльзас",
    "Amalfi Coast": "Амальфитанское побережье",
    "Amman": "Амман",
    "Amsterdam": "Амстердам",
    "Anapa": "Анапа",
    "Andorra la Vella": "Андорра-ла-Велья",
    "Ankara": "Анкара",
    "Antalya": "Анталья",
    "Antananarivo": "Антананариву",
    "Antigua Guatemala": "Антигуа-Гватемала",
    "Antwerpen": "Антверпен",
    "Aqaba": "Акаба",
    "Arequipa": "Арекипа",
    "Arkhangelsk": "Архангельск",
    "Arusha": "Аруша",
    "Ashgabat": "Ашхабад",
    "Asmara": "Асмэра",
    "Astana": "Астана",
    "Astrakhan": "Астрахань",
    "Asuncion": "Асунсьон",
    "Asunción": "Асунсьон",
    "Aswan": "Асуан",
    "Atacama": "Атакама",
    "Athens": "Афины",
    "Atlanta": "Атланта",
    "Auckland": "Окленд",
    "Avarua": "Аваруа",
    "Azores": "Азорские острова",
    "Bagan": "Баган",
    "Baku": "Баку",
    "Bali": "Бали",
    "Bangkok": "Бангкок",
    "Barcelona": "Барселона",
    "Bari": "Бари",
    "Bariloche": "Барилоче",
    "Barnaul": "Барнаул",
    "Beijing": "Пекин",
    "Beirut": "Бейрут",
    "Belgrade": "Белград",
    "Berlin": "Берлин",
    "Bern": "Берн",
    "Bishkek": "Бишкек",
    "Blue Mountains": "Голубые горы",
    "Bodrum": "Бодрум",
    "Boston": "Бостон",
    "Bratislava": "Братислава",
    "Bruges": "Брюгге",
    "Brussels": "Брюссель",
    "Bucharest": "Бухарест",
    "Budapest": "Будапешт",
    "Buenos Aires": "Буэнос-Айрес",
    "Cairo": "Каир",
    "Cancun": "Канкун",
    "Cape Town": "Кейптаун",
    "Casablanca": "Касабланка",
    "Cebu": "Себу",
    "Chicago": "Чикаго",
    "Colombo": "Коломбо",
    "Copenhagen": "Копенгаген",
    "Crete": "Крит",
    "Cusco": "Куско",
    "Delhi": "Дели",
    "Doha": "Доха",
    "Dubai": "Дубай",
    "Dushanbe": "Душанбе",
    "Edinburgh": "Эдинбург",
    "El Nido": "Эль-Нидо",
    "Florence": "Флоренция",
    "Frankfurt": "Франкфурт",
    "Fethiye": "Фетхие",
    "Fez": "Фес",
    "Fergana": "Фергана",
    "Fes": "Фес",
    "Gorno-Altaysk": "Горно-Алтайск",
    "Guangzhou": "Гуанчжоу",
    "George Town": "Джорджтаун",
    "Guatemala City": "Гватемала",
    "Hanoi": "Ханой",
    "Harbin": "Харбин",
    "Helsinki": "Хельсинки",
    "Ho Chi Minh City": "Хошимин",
    "Hong Kong": "Гонконг",
    "Hurghada": "Хургада",
    "Iceland Blue Lagoon": "Голубая лагуна",
    "Istanbul": "Стамбул",
    "Jakarta": "Джакарта",
    "Jerusalem": "Иерусалим",
    "Johannesburg": "Йоханнесбург",
    "Kazan": "Казань",
    "Koh Samui": "Самуи",
    "Komodo": "Комодо",
    "Kyoto": "Киото",
    "Kuala Lumpur": "Куала-Лумпур",
    "Kutaisi": "Кутаиси",
    "Lahore": "Лахор",
    "Langkawi": "Лангкави",
    "Las Vegas": "Лас-Вегас",
    "Lisbon": "Лиссабон",
    "Liverpool": "Ливерпуль",
    "Lofoten Islands": "Лофотенские острова",
    "London": "Лондон",
    "Los Angeles": "Лос-Анджелес",
    "Madrid": "Мадрид",
    "Male": "Мале",
    "Maldives": "Мальдивы",
    "Marrakech": "Марракеш",
    "Mecca": "Мекка",
    "Medellín": "Медельин",
    "Medina": "Медина",
    "Mexico City": "Мехико",
    "Milan": "Милан",
    "Minsk": "Минск",
    "Moscow": "Москва",
    "Monument Valley": "Долина Монументов",
    "Moorea": "Муреа",
    "Munich": "Мюнхен",
    "Nagasaki": "Нагасаки",
    "New Orleans": "Новый Орлеан",
    "New York": "Нью-Йорк",
    "Nice": "Ницца",
    "Nizhniy Novgorod": "Нижний Новгород",
    "Nukus": "Нукус",
    "Osaka": "Осака",
    "Oslo": "Осло",
    "Paris": "Париж",
    "Petra": "Петра",
    "Phuket": "Пхукет",
    "Plovdiv": "Пловдив",
    "Porto": "Порту",
    "Prague": "Прага",
    "Pristina": "Приштина",
    "Reykjavik": "Рейкьявик",
    "Riga": "Рига",
    "Riyadh": "Эр-Рияд",
    "Rome": "Рим",
    "Rotterdam": "Роттердам",
    "Samarkand": "Самарканд",
    "San Diego": "Сан-Диего",
    "San Francisco": "Сан-Франциско",
    "Santo Domingo Oeste": "Санто-Доминго-Оэсте",
    "Santorini": "Санторини",
    "Sapporo": "Саппоро",
    "Seoul": "Сеул",
    "Shanghai": "Шанхай",
    "Sharjah": "Шарджа",
    "Sharm El Sheikh": "Шарм-эш-Шейх",
    "Singapore": "Сингапур",
    "Sochi": "Сочи",
    "Stockholm": "Стокгольм",
    "Sydney": "Сидней",
    "Tallinn": "Таллин",
    "Tashkent": "Ташкент",
    "Tbilisi": "Тбилиси",
    "Tehran": "Тегеран",
    "Tel Aviv": "Тель-Авив",
    "The Bronx": "Бронкс",
    "Tokyo": "Токио",
    "Ulaanbaatar": "Улан-Батор",
    "Ushuaia": "Ушуая",
    "Valletta": "Валлетта",
    "Venice": "Венеция",
    "Vienna": "Вена",
    "Vilnius": "Вильнюс",
    "Warsaw": "Варшава",
    "Yerevan": "Ереван",
    "Zanzibar": "Занзибар",
    "Zurich": "Цюрих",
    "Amboseli": "Амбосели",
    "Budta": "Будта",
    "Camayenne": "Камайенн",
    "Chitwan": "Читван",
    "Colombo Fort": "Форт Коломбо",
    "El Aaiún": "Эль-Аюн",
    "Etosha": "Этоша",
    "Evaton": "Эватон",
    "Franz Josef": "Франц-Иосиф",
    "Kampung Baru Subang": "Кампунг-Бару-Субанг",
    "Kinosaki Onsen": "Киносаки-онсэн",
    "Landmannalaugar": "Ландманналёйгар",
    "Magome": "Магомэ",
    "Maldives South Ari": "Южный Ари-Атолл",
    "Mata-Utu": "Мата-Уту",
    "Nairobi Karen": "Карен, Найроби",
    "Natal Beach": "Натал",
    "Ngorongoro": "Нгоронгоро",
    "Olkhon": "Ольхон",
    "Pai": "Пай",
    "Port-aux-Français": "Порт-о-Франсе",
    "Rasapūdipalem": "Расапудипалем",
    "Rhine Valley": "Долина Рейна",
    "Rwanda Volcanoes": "Вулканы Руанды",
    "Shubrā al Khaymah": "Шубра-эль-Хейма",
    "Soshanguve": "Сошангуве",
    "Sulţānah": "Султана",
    "Talatona": "Талатона",
    "Tanzania Pemba": "о. Пемба",
    "Uganda Bwindi": "Бвинди",
    "Vang Vieng": "Ванг-Вьенг",
    "Whitsundays": "Уитсанди",
    "Yalata": "Ялата",
}

POI_EXACT_RU: dict[str, str] = {
    "Blue Mosque": "Голубая мечеть",
    "Colosseum": "Колизей",
    "Eiffel Tower": "Эйфелева башня",
    "Grand Bazaar": "Гранд-базар",
    "Hagia Sophia": "Айя-София",
    "Louvre Museum": "Лувр",
    "Notre-Dame Cathedral": "Собор Парижской Богоматери",
    "Sagrada Familia": "Саграда Фамилия",
    "Tower of London": "Лондонский Тауэр",
}

_CYRILLIC_RE = re.compile("[А-Яа-яЁё]")


def has_cyrillic(value: str | None) -> bool:
    return bool(value and _CYRILLIC_RE.search(value))


def translate_destination_name(name: str | None) -> str | None:
    if not name:
        return name
    if has_cyrillic(name):
        return name
    if name in DESTINATION_RU:
        return DESTINATION_RU[name]

    replacements = [
        (" Islands", "ские острова"),
        (" Island", " остров"),
        (" Coast", "ское побережье"),
        (" Mountains", "ские горы"),
        (" Mountain", " гора"),
        (" National Park", " национальный парк"),
        (" City", ""),
    ]
    for suffix, ru_suffix in replacements:
        if name.endswith(suffix):
            base = name[: -len(suffix)]
            return f"{DESTINATION_RU.get(base, base)}{ru_suffix}"
    return name


def translate_poi_name(name: str | None) -> str | None:
    if not name:
        return name
    if has_cyrillic(name):
        return name
    if name in POI_EXACT_RU:
        return POI_EXACT_RU[name]

    patterns = [
        (r"^(.+) Museum$", "Музей {0}"),
        (r"^(.+) Cathedral$", "Собор {0}"),
        (r"^(.+) Church$", "Церковь {0}"),
        (r"^(.+) Mosque$", "Мечеть {0}"),
        (r"^(.+) Temple$", "Храм {0}"),
        (r"^(.+) Palace$", "Дворец {0}"),
        (r"^(.+) Castle$", "Замок {0}"),
        (r"^(.+) Tower$", "Башня {0}"),
        (r"^(.+) Bridge$", "Мост {0}"),
        (r"^(.+) Square$", "Площадь {0}"),
        (r"^(.+) Park$", "Парк {0}"),
        (r"^(.+) Garden$", "Сад {0}"),
        (r"^(.+) Beach$", "Пляж {0}"),
        (r"^(.+) Market$", "Рынок {0}"),
    ]
    for pattern, template in patterns:
        match = re.match(pattern, name)
        if match:
            return template.format(translate_destination_name(match.group(1)) or match.group(1))
    return name
